name: Issue Report
description: Report a bug, request a feature, or ask a question
title: "[Issue]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue or suggest a feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue or feature request
      placeholder: Describe what the issue is or what feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (for bugs)
      description: If this is a bug, please provide steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: "N/A (not a bug)"
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g., Windows 10, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121] (if applicable)
        - Node.js version: [e.g., 18.17.0]
        - Version: [e.g., v1.2.3 or commit hash]
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or error logs to help explain your issue
      placeholder: Paste screenshots, error messages, or console logs here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or information about the issue
      placeholder: Add any other context about the issue here...
    validations:
      required: false

  - type: dropdown
    id: willing-to-work
    attributes:
      label: Are you willing to work on this issue?
      description: Let us know if you're interested in contributing a fix or implementation
      options:
        - Yes, I'd like to work on this
        - No, but I can help test
        - No, just reporting
    validations:
      required: true

